#
# spec file for package sys-inspector
#
# Copyright (c) 2026 Mario Luz
#

Name:           sys-inspector
Version:        0.90.00
Release:        1%{?dist}
Summary:        eBPF-based System Inspector and Forensic Tool (Multi-Agent/Web)

License:        GPL-3.0-only
URL:            https://github.com/mariosergiosl/sys-inspector
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

# Build Dependencies
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  fdupes

# Runtime Dependencies (CRITICAL for eBPF and Web)
Requires:       python3
Requires:       python3-bcc
Requires:       python3-Flask
Requires:       python3-cryptography
Requires:       python3-PyYAML
Requires:       kernel-devel
Requires:       binutils

%description
Sys-Inspector is an advanced observability tool leveraging eBPF technology.
It provides real-time analysis of:
- Process Execution (execve) with Hash Calculation
- File I/O (openat, vfs_read/write) with Zoning/HCTL info
- Network Connections (TCPv4)
- Memory Usage (RSS vs VSZ)
- Security Contexts (SSH Origin, Sudo, AppArmor)
- Multi-Agent Fleet Monitoring (Web Dashboard)
- Forensic Time Machine (Historical Snapshots)

Designed for SREs and Forensic Analysts.

%prep
%setup -q

%build
%python3_build

%install
%python3_install
# Fix duplicate files if any
%fdupes %{buildroot}%{python3_sitelib}

%files
%doc README.md ROADMAP.md CHANGELOG.md
%license LICENSE.md
%{_bindir}/sys-inspector
# Capture all top-level modules generated by the new architecture
%{python3_sitelib}/*

%changelog
* Mon Mar 16 2026 Mario Luz <mario.mssl@gmail.com> - 0.90.00
- Release v0.90.00: Multi-Agent Architecture, Fleet View, and Time Machine.
* Fri Nov 28 2025 Mario Luz <mario.mssl@gmail.com> - 0.20.0
- Release v0.20.0: Enterprise Forensic features, HCTL mapping, and HTML Reporting.