# ==============================================================================
# FILE: sys-inspector.spec
# DESCRIPTION: RPM Spec file for Sys-Inspector (v0.90.12)
# AUTHOR: Mario Luz
# ==============================================================================

Name:           sys-inspector
Version:        0.91.0
Release:        1%{?dist}
Summary:        System inspector and forensic tool using eBPF (Multi-Agent/Web)

Group:          System/Monitoring
License:        AGPL-3.0-only
URL:            https://github.com/mariosergiosl/sys-inspector
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

# Build Dependencies
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  fdupes
BuildRequires:  systemd-rpm-macros

# Runtime Dependencies (CRITICAL for eBPF and Web)
Requires:       python3
Requires:       python3-bcc
Requires:       python3-Flask
Requires:       python3-cryptography
Requires:       python3-PyYAML
Requires:       kernel-devel
Requires:       binutils

%{?systemd_requires}

%description
Sys-Inspector is an advanced observability tool leveraging eBPF technology.
It provides real-time analysis of process execution, file I/O, network
connections, and security contexts.
It provides real-time analysis of:
- Process Execution (execve) with Hash Calculation
- File I/O (openat, vfs_read/write) with Zoning/HCTL info
- Network Connections (TCPv4)
- Memory Usage (RSS vs VSZ)
- Security Contexts (SSH Origin, Sudo, AppArmor)
- Multi-Agent Fleet Monitoring (Web Dashboard)
- Forensic Time Machine (Historical Snapshots)
It ships a Multi-Agent architecture, Fleet View, FHS compliant paths and
native systemd integration.
Designed for SREs and Forensic Analysts.

%prep
%setup -q

%build
%python3_build

%install
%python3_install
# Fix duplicate files if any
%fdupes %{buildroot}%{python3_sitelib}

# Create FHS state and log directories
mkdir -p %{buildroot}/etc/sys-inspector
mkdir -p %{buildroot}/var/lib/sys-inspector
mkdir -p %{buildroot}/var/log/sys-inspector/reports
# SUSE Policy: Move systemd unit file from /etc to /usr/lib
mkdir -p %{buildroot}%{_unitdir}
if [ -f %{buildroot}/etc/systemd/system/sys-inspector.service ]; then
    mv %{buildroot}/etc/systemd/system/sys-inspector.service %{buildroot}%{_unitdir}/
fi
# SUSE convention: rc symlink for the service (rcsys-inspector -> service),
# fixes rpmlint suse-missing-rclink.
mkdir -p %{buildroot}%{_sbindir}
ln -sf %{_sbindir}/service %{buildroot}%{_sbindir}/rc%{name}

%pre
%service_add_pre sys-inspector.service

%post
%service_add_post sys-inspector.service

%preun
%service_del_preun sys-inspector.service

%postun
%service_del_postun sys-inspector.service

%files
%defattr(-,root,root,-)
%doc README.md ROADMAP.md CHANGELOG.md
%license LICENSE.md
# Binaries and Libraries, capture all top-level modules generated by the new architecture
%{_bindir}/sys-inspector
%{_bindir}/chaos_maker.sh
%{_bindir}/setup_env.sh
%{_bindir}/install_deps.sh
%{_bindir}/install_service.bash
%{_bindir}/generate_keys.py
%{_sbindir}/rcsys-inspector
%{python3_sitelib}/*

# ==============================================================================
# Configuration and systemd files
# ==============================================================================
# Configuration Files (FHS)
%dir /etc/sys-inspector
%config(noreplace) /etc/sys-inspector/config.yaml
# Systemd Unit File
%{_unitdir}/sys-inspector.service
# State and Log Directories (FHS)
%dir %attr(0750,root,root) /var/lib/sys-inspector
%dir %attr(0750,root,root) /var/log/sys-inspector
%dir %attr(0750,root,root) /var/log/sys-inspector/reports

%changelog
* Thu Aug 06 2026 Mario Luz <mario.mssl@gmail.com> - 0.91.0-1
- Added: normalized Finding entity (single severity scale, explicit source, MITRE ATT&CK technique, attached evidence) and a persistence collector covering systemd units, cron/at, startup scripts, ld.so.preload, kernel module autoload, udev rules, PAM stacks and per-user authorized_keys.
- Added: first automated test suite (pytest) wired into CI.
- Changed: all execution modes unified on a single encrypted storage model and data shape; live and server modes restored.
- Fixed: snapshot hot columns were always zero; alert badge showed a raw score; host-controlled data was not escaped in the HTML report; rpmlint findings in the package.
* Sun Jul 12 2026 Mario Luz <mario.mssl@gmail.com> - 0.90.16-1
- Security: optional dashboard HTTP Basic Auth and HTTPS (self-signed auto-generation), XSS prevention in the Fleet/Inspector views, and setup-script PATH hardening.
- Fixed: pyproject/setup packaging conflict, honor general.log_level, leaf-node expander literal, duplicate EDR-WAIT badge, WARN score tooltip, and false-positive NET ERR on kernel threads.
- Changed: toolbar active-state indicator and symmetric Process By / Filters icons.
* Wed Mar 18 2026 Mario Luz <mario.mssl@gmail.com> - 0.90.14
- Release v0.90.14: FHS compliant paths, systemd integration, and PyPI and OBS sync.